/**
 * audit-actions.ts · Catálogo de acciones registrables
 *
 * Cada acción tiene: action key, entity, severity por defecto, label legible.
 * Importar las constantes y usar tipos para evitar typos.
 */

// ─── ACTION KEYS ─────────────────────────────────────────────────────

export const AUDIT_ACTIONS = {
  // Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  // POS / Orden
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_ITEM_ADDED: "ORDER_ITEM_ADDED",
  ORDER_ITEM_QTY_CHANGED: "ORDER_ITEM_QTY_CHANGED",
  ORDER_ITEM_NOTE_EDITED: "ORDER_ITEM_NOTE_EDITED",
  ORDER_ITEM_REMOVED: "ORDER_ITEM_REMOVED",      // antes de cocina
  ORDER_ITEM_CANCELED: "ORDER_ITEM_CANCELED",    // ya en cocina (con motivo)
  ORDER_SENT_KITCHEN: "ORDER_SENT_KITCHEN",
  ORDER_CHECKOUT: "ORDER_CHECKOUT",
  ORDER_CANCELED: "ORDER_CANCELED",

  // Sale (genérico)
  SALE_CREATED: "SALE_CREATED",
  SALE_REFUNDED: "SALE_REFUNDED",

  // Inventory
  INVENTORY_ITEM_CREATED: "INVENTORY_ITEM_CREATED",
  INVENTORY_ITEM_EDITED: "INVENTORY_ITEM_EDITED",
  INVENTORY_ITEM_DEACTIVATED: "INVENTORY_ITEM_DEACTIVATED",
  INVENTORY_ITEM_REACTIVATED: "INVENTORY_ITEM_REACTIVATED",
  INVENTORY_MOVEMENT_IN: "INVENTORY_MOVEMENT_IN",
  INVENTORY_MOVEMENT_OUT: "INVENTORY_MOVEMENT_OUT",
  INVENTORY_MOVEMENT_ADJUST: "INVENTORY_MOVEMENT_ADJUST",
  INVENTORY_MOVEMENT_TRANSFER: "INVENTORY_MOVEMENT_TRANSFER",

  // Menu (catálogo restaurante)
  MENU_ITEM_CREATED: "MENU_ITEM_CREATED",
  MENU_ITEM_EDITED: "MENU_ITEM_EDITED",
  MENU_ITEM_DELETED: "MENU_ITEM_DELETED",
  MENU_PRICE_CHANGED: "MENU_PRICE_CHANGED",

  // Expenses
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_EDITED: "EXPENSE_EDITED",
  EXPENSE_DELETED: "EXPENSE_DELETED",

  // Requisitions
  REQUISITION_CREATED: "REQUISITION_CREATED",
  REQUISITION_APPROVED: "REQUISITION_APPROVED",
  REQUISITION_REJECTED: "REQUISITION_REJECTED",
  REQUISITION_DELIVERED: "REQUISITION_DELIVERED",

  // Users / Admin
  USER_CREATED: "USER_CREATED",
  USER_EDITED: "USER_EDITED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",

  // Hotel
  RESERVATION_CREATED: "RESERVATION_CREATED",
  RESERVATION_EDITED: "RESERVATION_EDITED",
  RESERVATION_CANCELED: "RESERVATION_CANCELED",
  CHECKIN: "CHECKIN",
  CHECKOUT_HOTEL: "CHECKOUT_HOTEL",

  // Shifts / Cashpoint
  SHIFT_OPENED: "SHIFT_OPENED",
  SHIFT_CLOSED: "SHIFT_CLOSED",

  // Misc edits
  GENERIC_EDIT: "GENERIC_EDIT",
  GENERIC_DELETE: "GENERIC_DELETE",
} as const;

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];

// ─── SEVERIDADES POR DEFECTO ─────────────────────────────────────────
// LOW: acciones rutinarias
// MEDIUM: edits con impacto
// HIGH: deletes, cancelaciones, ajustes manuales
// CRITICAL: cambios de rol, refunds, reset de password

export const ACTION_SEVERITY: Record<string, "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"> = {
  LOGIN_SUCCESS: "LOW",
  LOGIN_FAILED: "MEDIUM",
  LOGOUT: "LOW",

  ORDER_CREATED: "LOW",
  ORDER_ITEM_ADDED: "LOW",
  ORDER_ITEM_QTY_CHANGED: "LOW",
  ORDER_ITEM_NOTE_EDITED: "LOW",
  ORDER_ITEM_REMOVED: "LOW",
  ORDER_ITEM_CANCELED: "HIGH",
  ORDER_SENT_KITCHEN: "LOW",
  ORDER_CHECKOUT: "LOW",
  ORDER_CANCELED: "HIGH",

  SALE_CREATED: "LOW",
  SALE_REFUNDED: "CRITICAL",

  INVENTORY_ITEM_CREATED: "LOW",
  INVENTORY_ITEM_EDITED: "MEDIUM",
  INVENTORY_ITEM_DEACTIVATED: "HIGH",
  INVENTORY_ITEM_REACTIVATED: "MEDIUM",
  INVENTORY_MOVEMENT_IN: "LOW",
  INVENTORY_MOVEMENT_OUT: "LOW",
  INVENTORY_MOVEMENT_ADJUST: "HIGH",
  INVENTORY_MOVEMENT_TRANSFER: "MEDIUM",

  MENU_ITEM_CREATED: "MEDIUM",
  MENU_ITEM_EDITED: "MEDIUM",
  MENU_ITEM_DELETED: "HIGH",
  MENU_PRICE_CHANGED: "MEDIUM",

  EXPENSE_CREATED: "LOW",
  EXPENSE_EDITED: "MEDIUM",
  EXPENSE_DELETED: "HIGH",

  REQUISITION_CREATED: "LOW",
  REQUISITION_APPROVED: "MEDIUM",
  REQUISITION_REJECTED: "MEDIUM",
  REQUISITION_DELIVERED: "LOW",

  USER_CREATED: "MEDIUM",
  USER_EDITED: "MEDIUM",
  USER_DEACTIVATED: "HIGH",
  USER_ROLE_CHANGED: "CRITICAL",
  USER_PASSWORD_RESET: "CRITICAL",

  RESERVATION_CREATED: "LOW",
  RESERVATION_EDITED: "MEDIUM",
  RESERVATION_CANCELED: "HIGH",
  CHECKIN: "LOW",
  CHECKOUT_HOTEL: "LOW",

  SHIFT_OPENED: "LOW",
  SHIFT_CLOSED: "LOW",

  GENERIC_EDIT: "MEDIUM",
  GENERIC_DELETE: "HIGH",
};

// ─── LABELS LEGIBLES PARA UI ─────────────────────────────────────────

export const ACTION_LABELS: Record<string, string> = {
  LOGIN_SUCCESS: "Inicio de sesión",
  LOGIN_FAILED: "Login fallido",
  LOGOUT: "Cierre de sesión",

  ORDER_CREATED: "Abrió orden",
  ORDER_ITEM_ADDED: "Agregó platillo",
  ORDER_ITEM_QTY_CHANGED: "Cambió cantidad",
  ORDER_ITEM_NOTE_EDITED: "Editó nota",
  ORDER_ITEM_REMOVED: "Quitó platillo",
  ORDER_ITEM_CANCELED: "Canceló platillo en cocina",
  ORDER_SENT_KITCHEN: "Envió a cocina",
  ORDER_CHECKOUT: "Cobró orden",
  ORDER_CANCELED: "Canceló orden",

  SALE_CREATED: "Registró venta",
  SALE_REFUNDED: "Reembolsó venta",

  INVENTORY_ITEM_CREATED: "Creó producto",
  INVENTORY_ITEM_EDITED: "Editó producto",
  INVENTORY_ITEM_DEACTIVATED: "Desactivó producto",
  INVENTORY_ITEM_REACTIVATED: "Reactivó producto",
  INVENTORY_MOVEMENT_IN: "Entrada de inventario",
  INVENTORY_MOVEMENT_OUT: "Salida de inventario",
  INVENTORY_MOVEMENT_ADJUST: "Ajuste de inventario",
  INVENTORY_MOVEMENT_TRANSFER: "Transferencia de inventario",

  MENU_ITEM_CREATED: "Creó platillo en menú",
  MENU_ITEM_EDITED: "Editó platillo del menú",
  MENU_ITEM_DELETED: "Eliminó platillo del menú",
  MENU_PRICE_CHANGED: "Cambió precio",

  EXPENSE_CREATED: "Registró gasto",
  EXPENSE_EDITED: "Editó gasto",
  EXPENSE_DELETED: "Eliminó gasto",

  REQUISITION_CREATED: "Creó requisición",
  REQUISITION_APPROVED: "Aprobó requisición",
  REQUISITION_REJECTED: "Rechazó requisición",
  REQUISITION_DELIVERED: "Entregó requisición",

  USER_CREATED: "Creó usuario",
  USER_EDITED: "Editó usuario",
  USER_DEACTIVATED: "Desactivó usuario",
  USER_ROLE_CHANGED: "Cambió rol de usuario",
  USER_PASSWORD_RESET: "Reseteó contraseña",

  RESERVATION_CREATED: "Creó reservación",
  RESERVATION_EDITED: "Editó reservación",
  RESERVATION_CANCELED: "Canceló reservación",
  CHECKIN: "Check-in",
  CHECKOUT_HOTEL: "Check-out",

  SHIFT_OPENED: "Abrió turno",
  SHIFT_CLOSED: "Cerró turno",

  GENERIC_EDIT: "Editó",
  GENERIC_DELETE: "Eliminó",
};

// ─── CATEGORÍAS PARA FILTROS UI ──────────────────────────────────────

export const ACTION_CATEGORIES: Record<string, string[]> = {
  Auth: ["LOGIN_SUCCESS", "LOGIN_FAILED", "LOGOUT"],
  POS: [
    "ORDER_CREATED", "ORDER_ITEM_ADDED", "ORDER_ITEM_QTY_CHANGED",
    "ORDER_ITEM_NOTE_EDITED", "ORDER_ITEM_REMOVED", "ORDER_ITEM_CANCELED",
    "ORDER_SENT_KITCHEN", "ORDER_CHECKOUT", "ORDER_CANCELED",
  ],
  Ventas: ["SALE_CREATED", "SALE_REFUNDED"],
  Inventario: [
    "INVENTORY_ITEM_CREATED", "INVENTORY_ITEM_EDITED",
    "INVENTORY_ITEM_DEACTIVATED", "INVENTORY_ITEM_REACTIVATED",
    "INVENTORY_MOVEMENT_IN", "INVENTORY_MOVEMENT_OUT",
    "INVENTORY_MOVEMENT_ADJUST", "INVENTORY_MOVEMENT_TRANSFER",
  ],
  Menú: ["MENU_ITEM_CREATED", "MENU_ITEM_EDITED", "MENU_ITEM_DELETED", "MENU_PRICE_CHANGED"],
  Gastos: ["EXPENSE_CREATED", "EXPENSE_EDITED", "EXPENSE_DELETED"],
  Requisiciones: ["REQUISITION_CREATED", "REQUISITION_APPROVED", "REQUISITION_REJECTED", "REQUISITION_DELIVERED"],
  Usuarios: ["USER_CREATED", "USER_EDITED", "USER_DEACTIVATED", "USER_ROLE_CHANGED", "USER_PASSWORD_RESET"],
  Hotel: ["RESERVATION_CREATED", "RESERVATION_EDITED", "RESERVATION_CANCELED", "CHECKIN", "CHECKOUT_HOTEL"],
  Turnos: ["SHIFT_OPENED", "SHIFT_CLOSED"],
};

export const SEVERITY_LABELS: Record<string, string> = {
  LOW: "Bajo",
  MEDIUM: "Medio",
  HIGH: "Alto",
  CRITICAL: "Crítico",
};

export const SEVERITY_COLORS: Record<string, string> = {
  LOW: "text-muted-foreground border-l-gray-300",
  MEDIUM: "text-blue-700 border-l-blue-400",
  HIGH: "text-amber-700 border-l-amber-500",
  CRITICAL: "text-red-700 border-l-red-500",
};
